# Using numpy to Read and Write CSV Files

In this lab, you will be learning how to read and write CSV 
(comma-separated value) files using the numpy module, as well 
as get further practice doing matrix manipulations using numpy. 
You must submit your final notebook on BlackBoard to get credit
for this lab.

## Problem 1

Reading CSV files can be done easily using numpy and the loadtxt method.
Download the CSV file located on BlackBoard along with this lab notebook
and store the data into a matrix named temps. NOTE: It will be helpful
if you download the CSV file from BlackBoard, then upload it into Jupyter.
Print out the values in temps. Use a method in the numpy module named 
genfromtxt, and look at the delimiter and names parameter attributes.
Make sure the names parameter is assigned the valuie of True.

In [1]:
import numpy as np

temps = np.genfromtxt('MICity.csv', delimiter=',', names=True)
print(temps)

[(2019., 1., 17., 0., 0., 31.36,  0. , 35.16, 26.34)
 (2019., 1., 18., 0., 0., 28.13,  0.1, 31.76, 25.64)
 (2019., 1., 19., 0., 0., 19.71,  9.7, 27.91,  6.16)
 (2019., 1., 20., 0., 0.,  5.81,  0. , 11.42,  0.51)
 (2019., 1., 21., 0., 0.,  6.56,  0. , 11.96,  0.28)
 (2019., 1., 22., 0., 0., 23.48, 13.7, 33.51, 11.01)
 (2019., 1., 23., 0., 0., 28.69, 13. , 33.78, 19.65)
 (2019., 1., 24., 0., 0., 17.95,  0. , 22.92,  4.89)]


## Problem 2

When you printed out temps, did it print out everything from the data file (Yes or No). If No, what was missing from the printout?

## Problem 3

The temps object contains a data attribute named dtypes (eg temps.dtype). Print ouit the data types for the temps object.
In the cell below the output, explain what the '<f8' signifies. 

In [2]:
print(temps.dtype)

[('Year', '<f8'), ('Month', '<f8'), ('Day', '<f8'), ('Hour', '<f8'), ('Minute', '<f8'), ('Temperature_daily_mean', '<f8'), ('Total_Precipitation', '<f8'), ('Temperature_daily_max', '<f8'), ('Temperature_daily_min', '<f8')]


## Problem 4

There exists a names attribute in the dtype tuple. Print out the dtype names for the temps object.

In [3]:
print(temps.dtype.names)

('Year', 'Month', 'Day', 'Hour', 'Minute', 'Temperature_daily_mean', 'Total_Precipitation', 'Temperature_daily_max', 'Temperature_daily_min')


## Problem 5

Print out the days column from the temps data.
Print out the daily nmean temperatures on a separate line. 

In [4]:
print(temps['Day'])
print(temps['Temperature_daily_mean'])

[17. 18. 19. 20. 21. 22. 23. 24.]
[31.36 28.13 19.71  5.81  6.56 23.48 28.69 17.95]


## Problem 6

Calculate the mean of the daily temperature means, the daily temperature mins and the daiy temperature maxes. Print out the results, all on the same line with labels (e.g. Mean Temp Ave: {}, Min Temp Ave: {}, Max Temp Ave: {}). Print to 2 significant digits.

In [5]:
print(temps['Temperature_daily_mean'])

[31.36 28.13 19.71  5.81  6.56 23.48 28.69 17.95]


In [6]:
aveTempMean = np.average(temps['Temperature_daily_mean'])
aveTempMin = np.average(temps['Temperature_daily_min'])
aveTempMax = np.average(temps['Temperature_daily_max'])
print('Mean Temp Ave: {:.2f}, Min Temp Ave: {:.2f}, Max Temp Ave: {:.2f}'.format(aveTempMean, aveTempMin, aveTempMax))

Mean Temp Ave: 20.21, Min Temp Ave: 11.81, Max Temp Ave: 26.05
