# NumPy Basics Lab

This lab gives you practice using the basics of numpy arrays. Complete the exercises shown and submit your completed notebook on BlackBoard to receive credit.

## Problem 1

Write a NumPy program to create a 6 element array with the values [0 2 4 6 8 10] and store it into a variable named array1. Print out the array.

In [1]:
import numpy as np

array1 = np.array([0,2,4,6,8,10])
print(array1)

[ 0  2  4  6  8 10]


## Problem 2

Create a 3x3 matrix with values ranging from 2 to 10, storing the matrix into a variable named mat1. Print out the matrix.

Expected Output:

[[ 2 3 4]
 [ 5 6 7]
[ 8 9 10]] 

In [2]:
mat1 = np.matrix([[2,3,4], [5,6,7], [8,9,10]])

print(mat1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## Problem 3

Create a 3x3 matrix with random floating point values ranging from 10.0 to 100.0. Store the result into a variable named mat2. Print out the matrix. Use the random module.

In [3]:
import random

mat2 = [[0,0,0],[0,0,0],[0,0,0]]

for x in range(3):
    for y in range(3):
        mat2[x][y] = round(random.uniform(10.0, 100.0), 1)
        
print(mat2)

[[44.0, 45.5, 38.2], [87.2, 57.7, 43.3], [24.3, 78.9, 73.6]]


## Problem 4

Multiply mat1 and mat2 and store the result into a variable named mat3, printing out the result.

In [4]:
mat3 = mat1 * mat2
print(mat3)

[[ 446.8  579.7  500.7]
 [ 913.3 1126.   966. ]
 [1379.8 1672.3 1431.3]]


## Problem 5

Do an element-wise multiplication of mat1 and mat2. Store the result into a matrix named mat4 and print the result.

In [5]:
mat4 = np.multiply(mat1, mat2)
print(mat4)

[[ 88.  136.5 152.8]
 [436.  346.2 303.1]
 [194.4 710.1 736. ]]
